apiVersion: v1
data:
  halt: YXBpVmVyc2lvbjogYXBwcy92MQpraW5kOiBEYWVtb25TZXQKbWV0YWRhdGE6CiAgY3JlYXRpb25UaW1lc3RhbXA6IG51bGwKICBsYWJlbHM6CiAgICBpZDogZHMtaW1wb3J0YW50CiAgICB1dWlkOiAxODQyNmEwYi01ZjU5LTRlMTAtOTIzZi1jMGUwNzhlODI0NjIKICBuYW1lOiBkcy1pbXBvcnRhbnQKc3BlYzoKICBzZWxlY3RvcjoKICAgIG1hdGNoTGFiZWxzOgogICAgICBpZDogZHMtaW1wb3J0YW50CiAgICAgIHV1aWQ6IDE4NDI2YTBiLTVmNTktNGUxMC05MjNmLWMwZTA3OGU4MjQ2MgogIHRlbXBsYXRlOgogICAgbWV0YWRhdGE6CiAgICAgIGNyZWF0aW9uVGltZXN0YW1wOiBudWxsCiAgICAgIGxhYmVsczoKICAgICAgICBpZDogZHMtaW1wb3J0YW50CiAgICAgICAgdXVpZDogMTg0MjZhMGItNWY1OS00ZTEwLTkyM2YtYzBlMDc4ZTgyNDYyCiAgICBzcGVjOgogICAgICB0b2xlcmF0aW9uczoKICAgICAgLSBlZmZlY3Q6IE5vU2NoZWR1bGUKICAgICAgICBrZXk6IG5vZGUtcm9sZS5rdWJlcm5ldGVzLmlvL21hc3RlcgogICAgICBjb250YWluZXJzOgogICAgICAtIGltYWdlOiBodHRwZDoyLjQtYWxwaW5lCiAgICAgICAgbmFtZTogaHR0cGQKICAgICAgICByZXNvdXJjZXM6IHt9Cg==
kind: Secret
metadata:
  creationTimestamp: null
  name: secret1
---
apiVersion: v1
data:
  pass: MTIzNA==
  user: dXNlcjE=
kind: Secret
metadata:
  creationTimestamp: null
  name: secret2
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
spec:
  volumes:
  - name: secret-data
    secret:
      secretName: secret1
  containers:
  - image: busybox:1.31.1
    name: secret-pod
    args: ['sh','-c','sleep 1d']
    resources: {}
    volumeMounts:
    - name: secret-data
      readOnly: true
      mountPath: /tmp/secret1
    env:
    - name: APP_USER
      valueFrom:
        secretKeyRef:
          name: secret2
          key: user
    - name: APP_PASS
      valueFrom:
        secretKeyRef:
          name: secret2
          key: pass
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
